### ISSUE TITLE
NFTDrawer issue

### ISSUE THREAD

**Issue by carlfairclough** [dmihal/maker-devcon-burner-wallet#16]
```
NFTDrawer.js:14 Uncaught (in promise) Error: Node error: {"message":"Attempting to run transaction which calls a contract function, but recipient address 0xab9b09af9fe05a1dc273735443d849109a38fa0c is not a contract address","code":-32000,"data":{"stack":"Error\n    at /Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/ganache-core/lib/statemanager.js:840:1\n    at /Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/ganache-core/lib/statemanager.js:254:1\n    at /Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/ganache-core/lib/blockchain_double.js:996:1\n    at e.exports.i.getCode (/Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/ethereumjs-account/index.js:48:1)\n    at /Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/ganache-core/lib/blockchain_double.js:990:1\n    at /Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/merkle-patricia-tree/baseTrie.js:77:1\n    at /Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/merkle-patricia-tree/baseTrie.js:461:1\n    at Object.return (/Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/merkle-patricia-tree/baseTrie.js:485:1)\n    at /Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/merkle-patricia-tree/baseTrie.js:276:1\n    at e (/Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/merkle-patricia-tree/baseTrie.js:521:1)\n    at /Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/merkle-patricia-tree/baseTrie.js:516:1\n    at /Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/merkle-patricia-tree/baseTrie.js:180:1\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","name":"r"}}
    at Function.validate (web3-providers.umd.js:127)
    at HttpProvider._callee$ (web3-providers.umd.js:810)
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:264)
    at Generator.prototype.<computed> [as next] (runtime.js:98)
    at asyncGeneratorStep (asyncToGenerator.js:3)
    at _next (asyncToGenerator.js:25)
```

**Comment by as-dr** [comment]
Isn't this a Ganache issue? Can I close this @carlfairclough ?
