### ISSUE TITLE
"Collectable contract not found"

### ISSUE THREAD

**Issue by as-dr** [dmihal/maker-devcon-burner-wallet#17]
I run `yarn start` and get:

```
Collectable contract not found, deploying
(node:99615) UnhandledPromiseRejectionWarning: Error: Node error: {"message":"Method eth_chainId not supported.","code":-32000,"data":{"stack":"Error: Method eth_chainId not supported.\n    at GethApiDouble.handleRequest (/Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-core/lib/subproviders/geth_api_double.js:67:16)\n    at next (/Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:116:18)\n    at GethDefaults.handleRequest (/Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-core/lib/subproviders/gethdefaults.js:15:12)\n    at next (/Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:116:18)\n    at SubscriptionSubprovider.FilterSubprovider.handleRequest (/Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-core/node_modules/web3-provider-engine/subproviders/filters.js:89:7)\n    at SubscriptionSubprovider.handleRequest (/Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-core/node_modules/web3-provider-engine/subproviders/subscriptions.js:136:49)\n    at next (/Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:116:18)\n    at DelayedBlockFilter.handleRequest (/Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-core/lib/subproviders/delayedblockfilter.js:31:3)\n    at next (/Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:116:18)\n    at RequestFunnel.handleRequest (/Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-core/lib/subproviders/requestfunnel.js:32:12)\n    at next (/Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:116:18)\n    at Web3ProviderEngine._handleAsync (/Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:103:3)\n    at Timeout._onTimeout (/Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:87:12)\n    at ontimeout (timers.js:469:11)\n    at tryOnTimeout (timers.js:304:5)\n    at Timer.listOnTimeout (timers.js:264:5)","name":"Error"}}
    at Function.validate (/Users/alexsingh/projects/maker-devcon-burner-wallet/local-wallet/node_modules/web3-providers/dist/web3-providers.cjs.js:114:18)
    at HttpProvider._callee$ (/Users/alexsingh/projects/maker-devcon-burner-wallet/local-wallet/node_modules/web3-providers/dist/web3-providers.cjs.js:710:61)
    at tryCatch (/Users/alexsingh/projects/maker-devcon-burner-wallet/local-wallet/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/Users/alexsingh/projects/maker-devcon-burner-wallet/local-wallet/node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.<computed> [as next] (/Users/alexsingh/projects/maker-devcon-burner-wallet/local-wallet/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/Users/alexsingh/projects/maker-devcon-burner-wallet/local-wallet/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/Users/alexsingh/projects/maker-devcon-burner-wallet/local-wallet/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
(node:99615) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:99615) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by as-dr** [comment]
Resolved -> Update Ganache 😅
